[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# This ensures your main site doesn't use the preview URL format
[context.production]
  # Your production settings here

# This disables deploy previews if you don't want them
[context.deploy-preview]
  # You can uncomment the line below to disable deploy previews
  # command = "echo 'Deploy previews disabled' && exit 0"
